# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/vieta/OneDrive/Desktop/School Stuff/Fall 2025/FPGA/Blinking_LEDs/Blinking_LEDs.cache/wt} [current_project]
set_property parent.project_path {C:/Users/vieta/OneDrive/Desktop/School Stuff/Fall 2025/FPGA/Blinking_LEDs/Blinking_LEDs.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/vieta/OneDrive/Desktop/School Stuff/Fall 2025/FPGA/Blinking_LEDs/Blinking_LEDs.srcs/sources_1/new/blinking_leds.v}}
read_xdc {{C:/Users/vieta/OneDrive/Desktop/School Stuff/Fall 2025/FPGA/Blinking_LEDs/Blinking_LEDs.srcs/constrs_1/new/pin.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/vieta/OneDrive/Desktop/School Stuff/Fall 2025/FPGA/Blinking_LEDs/Blinking_LEDs.srcs/constrs_1/new/pin.xdc}}]

synth_design -top blinking_leds -part xc7a35tcpg236-1
write_checkpoint -noxdef blinking_leds.dcp
catch { report_utilization -file blinking_leds_utilization_synth.rpt -pb blinking_leds_utilization_synth.pb }
