# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_in]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_in]
	
# Leds
set_property PACKAGE_PIN U16 [get_ports {parking_slots_avail[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots_avail[0]}]
set_property PACKAGE_PIN E19 [get_ports {parking_slots_avail[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots_avail[1]}]
set_property PACKAGE_PIN U19 [get_ports {parking_slots_avail[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots_avail[2]}]
set_property PACKAGE_PIN V19 [get_ports {parking_slots_avail[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots_avail[3]}]
set_property PACKAGE_PIN W18 [get_ports {parking_slots_avail[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots_avail[4]}]


# Switches
set_property PACKAGE_PIN V17 [get_ports {parking_slots[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots[0]}]
set_property PACKAGE_PIN V16 [get_ports {parking_slots[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots[1]}]
set_property PACKAGE_PIN W16 [get_ports {parking_slots[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots[2]}]
set_property PACKAGE_PIN W17 [get_ports {parking_slots[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots[3]}]
set_property PACKAGE_PIN W15 [get_ports {parking_slots[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {parking_slots[4]}]
	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]	

#enables
set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]