# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/vieta/OneDrive/Desktop/School Stuff/Fall 2025/FPGA/Seven_Segment_LED_Display/Seven_Segment_LED_Display.cache/wt} [current_project]
set_property parent.project_path {C:/Users/vieta/OneDrive/Desktop/School Stuff/Fall 2025/FPGA/Seven_Segment_LED_Display/Seven_Segment_LED_Display.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/vieta/OneDrive/Desktop/School Stuff/Fall 2025/FPGA/Seven_Segment_LED_Display/Seven_Segment_LED_Display.srcs/sources_1/new/seven_segment_led.v}}
synth_design -top seven_segment_led -part xc7a35tcpg236-1
write_checkpoint -noxdef seven_segment_led.dcp
catch { report_utilization -file seven_segment_led_utilization_synth.rpt -pb seven_segment_led_utilization_synth.pb }
